steps:
- name: 'gcr.io/cloud-builders/docker'
  # FIXME: バージョンを固定している部分って本当にこれでいいの？
  args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hono-mahjong-app-repo/api-image:${_TAG_VERSION}', '-f', './mahjong-hono/Dockerfile', '.' ]
  # env情報はsecret managerから取れるようにしたい
  env:
    - 'PORT=8080'
    # - 'DATABASE_URL=file:/tmp/prisma/dev.db'
images:
# FIXME: バージョンを固定している部分って本当にこれでいいの？
- 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hono-mahjong-app-repo/api-image:${_TAG_VERSION}'