steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hono-mahjong-app-repo/api-image:${_TAG_VERSION}',
        '-f',
        './Dockerfile',
        '--build-arg',
        'DATABASE_URL=${_DATABASE_URL}',
        '.',
      ]
    env:
      - 'PORT=8080'
      - 'DATABASE_URL=${_DATABASE_URL}'
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hono-mahjong-app-repo/api-image:${_TAG_VERSION}'

substitutions:
  _TAG_VERSION: 'latest'
  _DATABASE_URL: ''
