steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hono-mahjong-app-repo/api-image:${_TAG_VERSION}',
        '-f',
        './Dockerfile',
        '--build-arg',
        'DATABASE_URL=${_DATABASE_URL}',
        '--build-arg',
        'GCS_SA_KEY_PATH=${_GCS_SA_KEY_PATH}',
        '--build-arg',
        'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}',
        '--build-arg',
        'GCS_SA_KEY_OBJECT=${_GCS_SA_KEY_OBJECT}',
        '.',
      ]
    env:
      - 'PORT=8080'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'GCS_SA_KEY_PATH=${_GCS_SA_KEY_PATH}'
      - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
      - 'GCS_SA_KEY_OBJECT=${_GCS_SA_KEY_OBJECT}'
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/hono-mahjong-app-repo/api-image:${_TAG_VERSION}'

substitutions:
  _TAG_VERSION: 'latest'
  _DATABASE_URL: ''
  _GCS_SA_KEY_PATH: ''
  _GCS_BUCKET_NAME: ''
  _GCS_SA_KEY_OBJECT: ''