packages:
  - 'packages/*'

catalog:
  # Dependencies
  '@google-cloud/storage': ^7.16.0
  '@prisma/client': ^5.20.0
  
  # Dev Dependencies - Build & Dev Tools
  '@biomejs/biome': ^1.9.4
  '@types/node': ^20.11.17
  copyfiles: ^2.4.1
  prisma: ^5.20.0
  ts-node: ^10.9.2
  tsx: ^4.7.1
  typescript: ^4.9.4
  
  # Dev Dependencies - Testing
  '@vitest/coverage-v8': ^2.1.8
  vitest: ^2.1.8
  
  # Dev Dependencies - Hono & API
  '@hono/node-server': ^1.12.1
  '@hono/swagger-ui': ^0.4.0
  '@hono/zod-openapi': ^0.15.3
  hono: ^4.5.6
  zod: ^3.23.8
