name: Manual Deploy for Trigger

on:
  workflow_dispatch:
    inputs:
      trigger-name:
        description: 'Select trigger name'
        required: true
        type: choice
        options:
          - sample-event
          - trigger-upload-games-csv
          - trigger-upload-gcs

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: triggers
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/782457994312/locations/global/workloadIdentityPools/asobiba-github-actions/providers/asobiba-github-actions'
          service_account: 'github-actions-deployer@ysmt-dev.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy trigger
        run: |
          ls -la
          gcloud functions deploy ${{ inputs.trigger-name }} \
            --gen2 \
            --runtime=nodejs20 \
            --region=asia-northeast1 \
            --source=. \
            --trigger-event-filters="type=google.cloud.storage.object.v1.finalized" \
            --trigger-event-filters="bucket=mite-min-sai" \
            --entry-point ${{ inputs.trigger-name }} \
            --set-env-vars BUCKET_NAME=mite-min-sai \
            --set-env-vars API_ENDPOINT=${{ secrets.API_ENDPOINT }}
