name: Manual Deploy for Trigger

on:
  workflow_dispatch:
    inputs:
      trigger-name:
        description: 'Select trigger name'
        required: true
        type: choice
        options:
          - sample-event
          - trigger-upload-games-csv
          - trigger-upload-gcs

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: triggers
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Deploy trigger
        run: |
          gcloud functions deploy ${{ inputs.trigger-name }} \
            --gen2 \
            --runtime=nodejs20 \
            --region=asia-northeast1 \
            --source=. \
            --trigger-event-filters="type=google.cloud.storage.object.v1.finalized" \
            --trigger-event-filters="bucket=${{ secrets.GCS_BUCKET_NAME }}" \
            --entry-point ${{ inputs.trigger-name }} \
            --memory=2048MB \
            --cpu=1 \
            --set-env-vars BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }} \
            --set-env-vars API_ENDPOINT=${{ secrets.API_ENDPOINT }}
