name: Manual Deploy for Trigger

on:
  workflow_dispatch:
    inputs:
      trigger-name:
        description: 'Select trigger name'
        required: true
        type: choice
        options:
          - trigger-upload-games-csv
          - sample-event
      bucket-name:
        description: 'Select bucket name'
        required: true
        type: choice
        options:
          - ma-tano-upload-games

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: triggers
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/782457994312/locations/global/workloadIdentityPools/asobiba-github-actions/providers/asobiba-github-actions'
          service_account: 'github-actions-deployer@ysmt-dev.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy trigger
        run: |
          gcloud functions deploy ${{ inputs.trigger-name }} \
            --gen2 \
            --runtime=nodejs20 \
            --region=asia-northeast1 \
            --source=./dist \
            --trigger-event-filters="type=google.cloud.storage.object.v1.finalized" \
            --trigger-event-filters="bucket=${{ inputs.bucket-name }}" \
            --entry-point ${{ inputs.trigger-name }} \
            --set-env-vars BUCKET_NAME=${{ inputs.bucket-name }}
